name = "GridapMakie"
uuid = "41f30b06-6382-4b60-a5f7-79d86b35bf5d"
authors = ["Alberto F. Mart√≠n <alberto.f.martin@anu.edu.au>","Eric Neiva <eneiva@cimne.upc.edu>","Pau Riera <pau.riera.p@gmail.com>","Francesc Verdugo <fverdugo@cimne.upc.edu>", "Jan Weidner <jw3126@gmail.com>", "Other contributors"]
version = "0.1.2"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
FileIO = "1"
FillArrays = "1"
GLMakie = "0.10"
GeometryBasics = "0.3, 0.4"
Gridap = "0.16, 0.17,0.18"
Makie = "0.21"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
