name = "GridapMakie"
uuid = "41f30b06-6382-4b60-a5f7-79d86b35bf5d"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>", "Jan Weidner <jw3126@gmail.com>", "Other contributors"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MeshViz = "9ecf9c4f-6e5a-4b5e-83ae-06f2c7a661d8"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[compat]
Gridap = "0.16"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
